### ISSUE TITLE
Missing encoding for bundle-of-exports componentarg

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/component-model#28] opened 2022-04-25 16:13 UTC
Explainer.md has:
```
componentarg ::= (module <moduleidx>)
               | (component <componentidx>)
               | (instance <instanceidx>)
               | (func <funcidx>)
               | (value <valueidx>)
               | (type <typeidx>)
               | (instance <export>*)
```

Binary.md has:
```
componentarg ::= n:<name> 0x00 m:<moduleidx>                       => n (module m)
               | n:<name> 0x01 c:<componentidx>                    => n (component c)
               | n:<name> 0x02 i:<instanceidx>                     => n (instance i)
               | n:<name> 0x03 f:<funcidx>                         => n (func f)
               | n:<name> 0x04 v:<valueidx>                        => n (value v)
               | n:<name> 0x05 t:<typeidx>                         => n (type t)
```

The last arm of Explainder.md's componentarg, `instance <export>*`, doesn't appear to have a corresponding line in the binary encoding.

**Comment by lukewagner** [comment] 2022-04-25 21:12
Ah, this omission was intentional: the idea (explained by the last paragraph in the "Instance definitions" section) is that these "inline instances" are desugared at parse time into uses of out-of-line instance definitions (kindof like `typeuse`s in the core spec).

**Comment by peterhuene** [comment] 2022-06-03 00:53
@sunfishcode can confirm, but I think this issue can be closed by design.

We've since implemented the desugaring of passing an instance from a "bundle of exports" as an argument in our parser.

**Closed** 2022-06-03 00:55 UTC
